app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::get('/', function () {
    return view('welcome');
});


// Route::get('', function() {}):
// Route::get('', function() {}):

Route::auth();

Route::get('/home', 'HomeController@index');

Route::get('post/{id}', ['as'=>'home.post', 'uses'=>'AdminPostsController@post']);

Route::group(['middleware'=>'admin'], function() {
    Route::get('admin', function() {
        return view('admin.index');
    });

    Route::resource('admin/users', 'AdminUsersController');

    Route::resource('admin/posts', 'AdminPostsController');

    Route::resource('admin/categories', 'AdminCategoriesController');

    Route::resource('admin/media', 'AdminMediasController');
    
    // Route::get('admin/media/upload', ['as' => 'admin.media.upload', 'uses' => 'AdminMediasController@store']);

    Route::resource('admin/comments', 'PostCommentsController');

    Route::resource('admin/comments/replies', 'CommentRepliesController');


});

Route::group(['middleware'=>'auth'], function(){
    Route::post('comment/reply', 'CommentRepliesController@createReply');
});

app/Comment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    protected $fillable = ['post_id', 'author', 'email', 'photo', 'body', 'is_active'];
    
    public function replies()
    {
        return $this->hasMany('App\CommentReply');
    }

    public function post()
    {
        return $this->belongsTo('App\Post');
    }
}

resources/views/admin/comments/index.blade.php
@extends('layouts.admin')

@section('content')
    @if (count($comments) > 0)
    
    <h1>Comments</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Author</th>
                <th>Email</th>
                <th>Body</th>
            </tr>
        </thead>
        <tbody>
            @foreach($comments as $comment)
            <tr>
                <td>{{$comment->id}}</td>
                <td>{{$comment->author}}</td>
                <td>{{$comment->email}}</td>
                <td>{{$comment->body}}</td>
                <td><a href="{{route('home.post', $comment->post->id)}}">View Post</a></td>
                <td><a href="{{route('admin.comments.replies.show', $comment->id)}}">View Replies</a></td>
                <td>
                    @if ($comment->is_active == 1)
                        {!! Form::open(['method'=>'PATCH', 'action'=>['PostCommentsController@update', $comment]]) !!}

                        <input type="hidden" name="is_active" value="0">

                        <div class="form-group">
                            {!! Form::submit('Un-approve', ['class' =>'btn btn-success']) !!}
                        </div>
                        {!! Form::close() !!}
                    @else
                        {!! Form::open(['method'=>'PATCH', 'action'=>['PostCommentsController@update', $comment]]) !!}

                        <input type="hidden" name="is_active" value="1">

                        <div class="form-group">
                            {!! Form::submit('Approve', ['class' =>'btn btn-info']) !!}
                        </div>
                        {!! Form::close() !!}
                    @endif
                </td>
                <td>
                    {!! Form::open(['method'=>'DELETE', 'action'=>['PostCommentsController@destroy', $comment]]) !!}
                    <div class="form-group">
                        {!! Form::submit('Delete', ['class' =>'btn btn-danger']) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
            @endforeach
        </tbody>  
    </table>
        
    @else
        
        <h1 class="text-center">No Comments</h1>
    @endif
@endsection

resources/views/admin/comments/show.blade.php
@extends('layouts.admin')

@section('content')
    @if (count($comments) > 0)
    
    <h1>Comments</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Author</th>
                <th>Email</th>
                <th>Body</th>
            </tr>
        </thead>
        <tbody>
            @foreach($comments as $comment)
            <tr>
                <td>{{$comment->id}}</td>
                <td>{{$comment->author}}</td>
                <td>{{$comment->email}}</td>
                <td>{{$comment->body}}</td>
                <td><a href="{{route('home.post', $comment->post->id)}}">View Post</a></td>
                <td>
                    @if ($comment->is_active == 1)
                        {!! Form::open(['method'=>'PATCH', 'action'=>['PostCommentsController@update', $comment]]) !!}

                        <input type="hidden" name="is_active" value="0">

                        <div class="form-group">
                            {!! Form::submit('Un-approve', ['class' =>'btn btn-success']) !!}
                        </div>
                        {!! Form::close() !!}
                    @else
                        {!! Form::open(['method'=>'PATCH', 'action'=>['PostCommentsController@update', $comment]]) !!}

                        <input type="hidden" name="is_active" value="1">

                        <div class="form-group">
                            {!! Form::submit('Approve', ['class' =>'btn btn-info']) !!}
                        </div>
                        {!! Form::close() !!}
                    @endif
                </td>
                <td>
                    {!! Form::open(['method'=>'DELETE', 'action'=>['PostCommentsController@destroy', $comment]]) !!}
                    <div class="form-group">
                        {!! Form::submit('Delete', ['class' =>'btn btn-danger']) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
            @endforeach
        </tbody>  
    </table>
        
    @else
        
        <h1 class="text-center">No Comments</h1>
    @endif
@endsection