app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::get('/', function () {
    return view('welcome');
});


// Route::get('', function() {}):
// Route::get('', function() {}):

Route::auth();

Route::get('/home', 'HomeController@index');

Route::get('post/{id}', ['as'=>'home.post', 'uses'=>'AdminPostsController@post']);

Route::group(['middleware'=>'admin'], function() {
    Route::get('admin', function() {
        return view('admin.index');
    });

    Route::resource('admin/users', 'AdminUsersController');

    Route::resource('admin/posts', 'AdminPostsController');

    Route::resource('admin/categories', 'AdminCategoriesController');

    Route::resource('admin/media', 'AdminMediasController');
    
    // Route::get('admin/media/upload', ['as' => 'admin.media.upload', 'uses' => 'AdminMediasController@store']);

    Route::resource('admin/comments', 'PostCommentsController');

    Route::resource('admin/comments/replies', 'CommentRepliesController');


});

Route::group(['middleware'=>'auth'], function(){
    Route::post('comment/reply', 'CommentRepliesController@createReply');
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = ['name'];
}

resources/views/admin/categories/edit.blade.php
@extends('layouts.admin')


@section('content')
    <h1>Categories</h1>

    <div class="col-md-6">
        {!! Form::model($category, ['method'=>'PATCH', 'action'=>['AdminCategoriesController@update', $category]]) !!}
        <div class="form-group">
            {!! Form::label('name', 'name:') !!}
            {!! Form::text('name', null, ['class' =>'form-control']) !!}
        </div>
        <div class="form-group">
            {!! Form::submit('Update Category', ['class' =>'btn btn-primary col-sm-6']) !!}
        </div>
        {!! Form::close() !!}

        <div class="form-group">
            {!! Form::open(['method'=>'DELETE', 'action'=>['AdminCategoriesController@destroy', $category]]) !!}
            <div class="form-group">
                {!! Form::submit('Delete Category', ['class' =>'btn btn-danger col-sm-6']) !!}
            </div>
            {!! Form::close() !!}
        </div>
    </div>

    <div class="col-md-6">
            
    </div>
    
@endsection

resources/views/admin/categories/index.blade.php
@extends('layouts.admin')


@section('content')
    <h1>Categories</h1>

    <div class="col-md-6">
        {!! Form::open(['method'=>'POST', 'action'=>'AdminCategoriesController@store']) !!}
        <div class="form-group">
            {!! Form::label('name', 'name:') !!}
            {!! Form::text('name', null, ['class' =>'form-control']) !!}
        </div>
        <div class="form-group">
            {!! Form::submit('Create Category', ['class' =>'btn btn-primary']) !!}
        </div>
        {!! Form::close() !!}
    </div>

    <div class="col-md-6">

        @if ($categories)
        <table class="table">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Created</th>
                    <th>Updated</th>
                </tr>
            </thead>
            <tbody>
                @foreach($categories as $category)
                <tr>
                    <td>{{$category->id}}</td>
                    <td><a href="{{route('admin.categories.edit', $category)}}">{{$category->name}}</a></td>
                    <td>{{$category->created_at ? $category->created_at->diffForHumans() : 'no date'}}</td>
                    <td>{{$category->updated_at ? $category->updated_at->diffForHumans() : 'no date'}}</td>
                </tr>
                @endforeach
            </tbody>  
        </table>
        @endif
    </div>
    
@endsection